name: Convert Marp Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'  # Triggers on changes to any .md file
  pull_request:
    paths:
      - '**/*.md'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code and fetch all history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full commit history to compare changes

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install Marp CLI
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      # Convert changed .md files to .pdf if they contain 'marp: true'
      - name: Convert .md to .pdf
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD | grep '\.md$'); do
            if grep -q '^marp: true' "$file"; then
              echo "Exportant ${file%.md}"
              marp "$file" --pdf --output "${file%.md}.pdf"
            else
              echo "Skipping $file as it does not contain 'marp: true'"
            fi
          done

      # Commit and push the generated PDF files
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.pdf
          git commit -m "Add converted PDF files from Marp markdown"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
